export const products = [
  {
    id: 1,
    title: "White hoodies",
    description: "White in color",
    price: "2500",
    img: "https://media.istockphoto.com/photos/blank-hoodie-sweatshirt-color-white-front-arm-view-picture-id843947054",
    quantity: 1,
  },
  {
    id: 2,
    title: "Blue hoodies",
    description: "Blue in color",
    price: "2300",
    img: "https://media.istockphoto.com/photos/blank-hoodie-sweatshirt-color-blue-front-arm-view-picture-id844363472",
    quantity: 1,
  },
  {
    id: 3,
    title: "Green hoodies",
    description: "Green in color",
    price: "3500",
    img: "https://media.istockphoto.com/photos/blank-hoodie-sweatshirt-color-green-front-view-picture-id845813120",
    quantity: 1,
  },
  {
    id: 4,
    title: "Red hoodies",
    description: "Red in color",
    price: "4500",
    img: "https://media.istockphoto.com/photos/blank-hoodie-sweatshirt-color-red-back-view-on-white-background-picture-id1351057759",
    quantity: 1,
  },
  {
    id: 5,
    title: "Yellow hoodies",
    description: "Yellow in color",
    price: "2500",
    img: "https://media.istockphoto.com/photos/blank-hoodie-sweatshirt-color-yellow-front-view-on-white-background-picture-id1351277868?s=612x612",
    quantity: 1,
  },
  {
    id: 6,
    title: "Purple hoodies",
    description: "Purple in color",
    price: "3500",
    img: "https://media.istockphoto.com/photos/blank-hoodie-sweatshirt-color-purple-front-arm-view-on-white-picture-id1351477711?s=612x612",
    quantity: 1,
  },
  {
    id: 7,
    title: "Green hoodies",
    description: "Green in color",
    price: "2500",
    img: "https://media.istockphoto.com/photos/blank-hoodie-sweatshirt-color-green-front-view-picture-id845813120",
    quantity: 1,
  },
 
  {
    id: 9,
    title: "Maroon hoodies",
    description: "Maroon in color",
    price: "2500",
    img: "https://media.istockphoto.com/photos/blank-hoodie-sweatshirt-color-maroon-back-view-picture-id846243872",
    quantity: 1,
  },
];
